export enum Type {
      ADD_MANAGER = 'ADD_MANAGER',
      ADD_EMPLOYEE = 'ADD_EMPLOYEE',
      ADD_MESSAGE = 'ADD_MESSAGE',
      ADD_TEAM = 'ADD_TEAM'
    //   CHECK_ID = 'CHECK_ID',
    //   FETCH_EMPLOYEE_DETAILS = 'FETCH_EMPLOYEE_DETAILS',
    //   FETCH_MANAGER_DETAILS = 'FETCH_MANAGER_DETAILS'
  }